import Head from 'next/head'
import Clock from 'react-live-clock';
import React, { useState, useEffect } from 'react';

export default function Home() {
  const [month, setMonth] = useState('');
  const [day, setDay] = useState('');
  const [date, setDate] = useState('');

  useEffect(() => {
    const monthIndex = new Date().getMonth();
    const dayIndex = new Date().getDay();
    const date = new Date().getDate();

    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

    setDate(date)
    setMonth(monthNames[monthIndex]);
    setDay(dayNames[dayIndex]);
  }, []);



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <main>
          <div className="content" >
            <h1>Welcome!</h1>
            <h3><Clock
              format={'h:mm'}
              ticking={true} /></h3>
            <p id="date">{day}, {month} {date} </p>
          </div>
          <div className="inputs">
            <input type="text" id="username"></input>
            <input type="password" id="password"></input>
            <label className="rememberBox">
              <p>Remember me</p>
              <input type="checkbox"></input>
              <span className="checkmark"></span>
            </label>

            <button type="submit">LOGIN</button>
          </div>
        </main>
      </div>
    </>
  )
}
